=== catalinVoicu/ArtGallery/assets/xsds/artisti.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="artisti">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="artist">
        <xs:complexType>
          <xs:sequence>            
            <xs:element name="nume" type="xs:string"/>
            <xs:element name="data_nasterii" type="xs:string"/>
            <xs:element name="nationalitate" type="xs:string"/>
            <xs:element name="descriere" type="xs:string"/>
          </xs:sequence>
          <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== catalinVoicu/ArtGallery/assets/xmls/artisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<artisti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="file://C:\\Users\\Razvan\\Documents\\GitHub\\ArtGallery\\assets\\xsds\\artisti.xsd">
	<artist id="1">
		<nume>Artist 1</nume>
		<data_nasterii>Data 1</data_nasterii>
		<nationalitate>Nationalitate 1</nationalitate>
		<descriere>Descriere 1</descriere>
	</artist>
	<artist id="2">
		<nume>Artist 2</nume>
		<data_nasterii>Data 2</data_nasterii>
		<nationalitate>Nationalitate 2</nationalitate>
		<descriere>Descriere 2</descriere>
	</artist>
	<artist id="3">
		<nume>Artist 3</nume>
		<data_nasterii>Data 3</data_nasterii>
		<nationalitate>Nationalitate 3</nationalitate>
		<descriere>Descriere 3</descriere>
	</artist>
	<artist id="4">
		<nume>Artist 4</nume>
		<data_nasterii>Data 4</data_nasterii>
		<nationalitate>Nationalitate 4</nationalitate>
		<descriere>Descriere 4</descriere>
	</artist>
	<artist id="5">
		<nume>Artist 5</nume>
		<data_nasterii>Data 5</data_nasterii>
		<nationalitate>Nationalitate 5</nationalitate>
		<descriere>Descriere 5</descriere>
	</artist>
</artisti>
